//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAndes.ICC5103._202301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealStateForm
    {
        public int Id { get; set; }
        public int attentionNumber { get; set; }
        public bool natureOfTheDeed { get; set; }
        public string commune { get; set; }
        public string block { get; set; }
        public string property { get; set; }
        public int sheets { get; set; }
        public System.DateTime inscriptionDate { get; set; }
        public int inscriptionNumber { get; set; }
    }
}
